title: FTMW Scientific Instrument Simulator
description: A simulator for a Fourier Transform Microwave Scientific.
show_downloads: true
google_analytics:
theme: minima
minima:
  toc: false
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
